language: python

os:
  - linux
  
python:
  - "3.5"
  - "3.6"

install:
  - pip install numpy
  - pip install coverage
  - pip install codacy-coverage
  - pip install mypy

script:
  - ./run_test.sh
  - mypy --ignore-missing-import runtime_check